### ISSUE TITLE
About compiling

### ISSUE THREAD

**Issue by dungeonsnd** [draekko/android_libpcap_174_static_lib#1]
hi, friend,

I've compiled libpcap for Android for a few days, but can't compiled sucessfully.
But i've compiled very sucessfully with yours project.
I want to known what have you do with the official libpcap source code.
Thank you.

Jeffery 
Nanjing/China

**Comment by draekko** [comment]
I created a new Android.mk only. I didn't alter any source code. Doing a diff between the 1.7.4 source code and mine should give you a better idea of whats different.

**Comment by draekko** [comment]
One thing to note I am using the latest ndk (as of today that is r10e).
